// ECCC City Page Weather feature IDs validated against the realtime collection.
// The search API is used instead of direct item URLs because collection item
// lookup is inconsistent for this experimental endpoint.
export const canadianCities = Object.freeze([
  { id:"bc-74", name:"Vancouver", province:"BC", region:"West", query:"Vancouver" },
  { id:"bc-85", name:"Victoria", province:"BC", region:"West", query:"Victoria" },
  { id:"bc-48", name:"Kelowna", province:"BC", region:"West", query:"Kelowna" },
  { id:"bc-45", name:"Kamloops", province:"BC", region:"West", query:"Kamloops" },
  { id:"bc-20", name:"Nanaimo", province:"BC", region:"West", query:"Nanaimo" },
  { id:"bc-79", name:"Prince George", province:"BC", region:"West", query:"Prince George" },
  { id:"ab-52", name:"Calgary", province:"AB", region:"Prairies", query:"Calgary" },
  { id:"ab-50", name:"Edmonton", province:"AB", region:"Prairies", query:"Edmonton" },
  { id:"ab-29", name:"Red Deer", province:"AB", region:"Prairies", query:"Red Deer" },
  { id:"ab-30", name:"Lethbridge", province:"AB", region:"Prairies", query:"Lethbridge" },
  { id:"sk-40", name:"Saskatoon", province:"SK", region:"Prairies", query:"Saskatoon" },
  { id:"sk-32", name:"Regina", province:"SK", region:"Prairies", query:"Regina" },
  { id:"mb-38", name:"Winnipeg", province:"MB", region:"Prairies", query:"Winnipeg" },
  { id:"mb-52", name:"Brandon", province:"MB", region:"Prairies", query:"Brandon" },
  { id:"on-143", name:"Toronto", province:"ON", region:"Central", query:"Toronto" },
  { id:"on-118", name:"Ottawa", province:"ON", region:"Central", query:"Ottawa" },
  { id:"on-24", name:"Mississauga", province:"ON", region:"Central", query:"Mississauga" },
  { id:"on-77", name:"Hamilton", province:"ON", region:"Central", query:"Hamilton" },
  { id:"on-137", name:"London", province:"ON", region:"Central", query:"London Ontario" },
  { id:"on-82", name:"Kitchener-Waterloo", province:"ON", region:"Central", query:"Kitchener Waterloo" },
  { id:"on-94", name:"Windsor", province:"ON", region:"Central", query:"Windsor" },
  { id:"on-40", name:"Greater Sudbury", province:"ON", region:"Central", query:"Greater Sudbury" },
  { id:"on-100", name:"Thunder Bay", province:"ON", region:"Central", query:"Thunder Bay" },
  { id:"on-69", name:"Kingston", province:"ON", region:"Central", query:"Kingston Ontario" },
  { id:"qc-147", name:"Montréal", province:"QC", region:"Central", query:"Montréal" },
  { id:"qc-133", name:"Québec", province:"QC", region:"Central", query:"Québec" },
  { id:"qc-126", name:"Gatineau", province:"QC", region:"Central", query:"Gatineau" },
  { id:"qc-136", name:"Sherbrooke", province:"QC", region:"Central", query:"Sherbrooke" },
  { id:"qc-130", name:"Trois-Rivières", province:"QC", region:"Central", query:"Trois-Rivières" },
  { id:"qc-166", name:"Saguenay", province:"QC", region:"Central", query:"Saguenay" },
  { id:"nb-29", name:"Fredericton", province:"NB", region:"Atlantic", query:"Fredericton" },
  { id:"nb-36", name:"Moncton", province:"NB", region:"Atlantic", query:"Moncton" },
  { id:"nb-23", name:"Saint John", province:"NB", region:"Atlantic", query:"Saint John New Brunswick" },
  { id:"ns-19", name:"Halifax", province:"NS", region:"Atlantic", query:"Halifax" },
  { id:"pe-5", name:"Charlottetown", province:"PE", region:"Atlantic", query:"Charlottetown" },
  { id:"nl-24", name:"St. John's", province:"NL", region:"Atlantic", query:"St. John's Newfoundland" },
  { id:"yt-16", name:"Whitehorse", province:"YT", region:"North", query:"Whitehorse" },
  { id:"nt-24", name:"Yellowknife", province:"NT", region:"North", query:"Yellowknife" },
  { id:"nu-21", name:"Iqaluit", province:"NU", region:"North", query:"Iqaluit" },
]);

export const regionColors = Object.freeze({ West:0x66c7f2, Prairies:0xf3bb67, Central:0xb797ff, Atlantic:0x67d6ad, North:0xf078a7 });
